# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        working-directory: ./sport-score-monitoring.web
        cache: 'npm'
    - name: npm i web
      working-directory: ./sport-score-monitoring.web
      run: npm ci
    - name: build web
      run: npm run build
    - name: npm i service
      working-directory: ./sport-score-monitoring.service
      run: npm ci
    - name: build service
      run: npm run build
    - name: test service
      run: npm run test
